variables:
  S3_ENDPOINT: $S3_ENDPOINT
  S3_ACCESS_KEY: $S3_ACCESS_KEY
  S3_SECRET_KEY: $S3_SECRET_KEY
  S3_BUCKET_PREFIX: $S3_BUCKET_PREFIX

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  image:
    name: minio/mc
    entrypoint: [""]
  script:
    - cd stream
    - mc alias set minio $S3_ENDPOINT $S3_ACCESS_KEY $S3_SECRET_KEY
    - mc mirror --overwrite --remove --exclude ".*" . minio/$S3_BUCKET_PATH/$CI_PROJECT_NAME/$CI_COMMIT_SHA/stream
  tags:
    - docker
